# Generated by Django 4.2.18 on 2025-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0002_note_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='remind_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
