# Generated by Django 4.2.18 on 2025-02-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder_app', '0003_alter_note_content_alter_note_remind_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='remind_date',
            field=models.DateTimeField(blank=True, help_text='Пример: 2025-02-09 22:10', null=True),
        ),
    ]
